### ISSUE TITLE
Sometimes the answer is a route that looks ridiculous, with a short walking distance segment, or multiple

### ISSUE THREAD

**Issue by KeetonMartin** [blahblahblah-/subwaydle#8]
Perhaps some routes should be excluded from the set of possible daily answers if one of their 3 segments is shorter than 0.5 miles?

What other potential solutions are there to this frustrating problem for users?

See screenshot. Can attach more if necessary. ![image](https://github.com/blahblahblah-/subwaydle/assets/25427567/1f16bcc8-27de-41af-b564-864ab4124887)

**Comment by KeetonMartin** [comment]
Another bad one today:
![image](https://github.com/blahblahblah-/subwaydle/assets/25427567/7cef0a8f-3324-4791-bdd6-1b7e4af95c96)

**Comment by KeetonMartin** [comment]
Another day, another unfortunate route due to bad transfers in Fidi 

![image](https://github.com/blahblahblah-/subwaydle/assets/25427567/0df137ae-449b-4247-8e7b-0acedea8c755)

**Comment by sunny-ng** [comment]
That's a great suggestion in regards of weeding out short segments. I'll look into the feasibility of incorporating that in future solutions.

**Comment by sunny-ng** [comment]
Alright, I tried your suggestion, and let's see how it goes. @KeetonMartin 

https://github.com/blahblahblah-/subwaydle/commit/e0230c046dc56a785c6fae5244f732a6dffd3fad?diff=unified&w=0#diff-12f3a74f4a9d89b5196f181f7027514d015ccda29c1550a0ebfd7056931db0e1R173

I'm going to close this issue for now. If this is still a problem, feel free to re-open this.

**Comment by KeetonMartin** [comment]
Got a weird one today. Is it possible this route was created because the 14th St. and sixth Avenue station and its transfers isn't properly accounted for with the L?

![image](https://github.com/user-attachments/assets/00033cbe-d4ee-4b84-92a1-01a8b0761a08)
